<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('App')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?= $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
                        ->prependStylesheet($this->basePath('css/style.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                        ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
        ?>

        <!-- Scripts -->
        <?= $this->headScript()
            ->prependFile($this->basePath('js/bootstrap.min.js'))
            ->prependFile($this->basePath('js/jquery-2.2.4.min.js'))
        ?>
    </head>
    <body>
        <div class="container">
            <div class="row">
                <!-- Page header -->
                <div class="col-md-4">
                    <div class="app-caption">App demo</div>
                </div>
                <div class="col-md-8">
                    <?php if($_SESSION['lang'] == 'eng'){ ?>
                        <li class="nav-item dropdown nav_lang">
                            <a class="nav-link dropdown-toggle" href="<?= $this->url('language', ['lang'=>'eng']); ?>" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Eng
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <!--<a class="dropdown-item" href="<?= $this->url('language', ['lang'=>'rus']); ?>">Рус</a>-->
                                <a class="dropdown-item" href="<?= $this->url('language', ['lang'=>'arm']); ?>">Հայ</a>
                            </div>
                        </li>
                    <?php }elseif($_SESSION['lang'] == 'rus'){ ?>
                        <li class="nav-item dropdown nav_lang">
                            <a class="nav-link dropdown-toggle" href="<?= $this->url('language', ['lang'=>'rus']); ?>" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Рус
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <!--<a class="dropdown-item" href="<?= $this->url('language', ['lang'=>'eng']); ?>">Eng</a>-->
                                <a class="dropdown-item" href="<?= $this->url('language', ['lang'=>'arm']); ?>">Հայ</a>
                            </div>
                        </li>
                    <?php  }elseif($_SESSION['lang'] == 'arm'){ ?>
                        <li class="nav-item dropdown nav_lang">
                            <a class="nav-link dropdown-toggle" href="<?= $this->url('language', ['lang'=>'arm']); ?>" id="navbarDropdownMenuLink" data-toggle="dropdown"
                               aria-haspopup="true" aria-expanded="false">
                                Հայ
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <a class="dropdown-item" href="<?= $this->url('language', ['lang'=>'eng']); ?>">Eng</a>
                                <!--<a class="dropdown-item" href="<?= $this->url('language', ['lang'=>'rus']); ?>">Рус</a>-->
                            </div>
                        </li>
                    <?php } ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Navigation bar -->
                    <?php
                    // Check if the activeMenuItemId passed to layout view model
                    // and if so, use it for setting active navbar item.
                    if (isset($activeMenuItemId)) {
                        $this->mainMenu()->setActiveItemId($activeMenuItemId);
                    }

                    // Render the navbar
                    echo $this->mainMenu()->render();
                    ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Breadcrumbs -->
                    <?= $this->pageBreadcrumbs()->render(); ?>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <!-- Page content placeholder -->
                    <?= $this->content; ?>
                </div>
            </div>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Your Company. All rights reserved.</p>
            </footer>
        </div>
        <?= $this->inlineScript() ?>
    </body>
</html>
