<?php
$this->headTitle('View Post');

$this->mainMenu()->setActiveItemId('type');

$this->pageBreadcrumbs()->setItems([
    'Home'=>$this->url('home'),
    'Posts'=>$this->url('postList', ['id'=>$post->getType()]),
    'View post'=>$this->url('application', ['action'=>'post', 'id'=>$post->getId()])
]);
?>

<h1>View Post:  <?= $this->escapeHtml($post->getTitle()) ?></h1>

<p>
    <a class="btn btn-default" href="<?= $this->url('main',
        ['action'=>'edit', 'id'=>$post->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
            <tr>
                <th>Title:</th>
                <td><?= $this->escapeHtml($post->getTitle()) ?></th>
            </tr>
            <tr>
                <th>Text:</th>
                <td><?= $this->escapeHtml($post->getText()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($post->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Image:</th>
                <td><img src="<?php echo $this->basePath('../data/upload/images/'); ?><?= $this->escapeHtml($post->getImage()) ?>" alt="photo" height="100" width="100"></th>
            </tr>
            <tr>
                <th>File:</th>
                <td><a href="<?php echo $this->basePath('../data/upload/pdf/'); ?><?= $this->escapeHtml($post->getFile()) ?>" download>Download</a></th>
            </tr>
        </table>
    </div>
</div>