<?php
$this->headTitle('Add Post');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Posts'=>$this->url('main'),
            'Add Post'=>$this->url('main', ['action'=>'add'])
            ]);

$form->get('text')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Text'
    ]);

$form->get('title')->setAttributes([
    'class'=>'form-control', 
    'placeholder'=>'Title'
    ]);

$form->get('type')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Type',
    ]);

$form->get('lang')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Language',
    ]);

$form->get('image')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Image',
    ]);

$form->get('file')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'File'
    ]);

$form->get('submit')->setAttributes(['class'=>'btn btn-primary']);

$form->prepare();
?>

<h1>Add Post</h1>

<p>
    Please fill out the following form and click the <i>Add</i> button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('title')); ?>
            <?= $this->formElement($form->get('title')); ?>
            <?= $this->formElementErrors($form->get('title')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('text')); ?>
            <?= $this->formElement($form->get('text')); ?>
            <?= $this->formElementErrors($form->get('text')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('type')); ?>
            <?= $this->formElement($form->get('type')); ?>
            <?= $this->formElementErrors($form->get('type')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('lang')); ?>
            <?= $this->formElement($form->get('lang')); ?>
            <?= $this->formElementErrors($form->get('lang')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('image')); ?>
            <?= $this->formElement($form->get('image')); ?>
            <?= $this->formElementErrors($form->get('image')); ?>
        </div>
        
        <div class="form-group">
            <?= $this->formLabel($form->get('file')); ?>
            <?= $this->formElement($form->get('file')); ?>
            <?= $this->formElementErrors($form->get('file')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>
        
        <?= $this->form()->closeTag(); ?>
    </div>    
</div>   

