<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Posts'=>$this->url('main'),
            ]);
?>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Text</th>
        <th>Title</th>
        <th>Language</th>
        <th>Image</th>
        <th>Date Created</th>
    </tr>
    
    <?php foreach ($posts as $post): ?>
    
    <tr>
        <td><?= $this->escapeHtml($post->getId()); ?></td>
        <td>
            <?= $this->escapeHtml($post->getType()); ?></a>
        </td>
        <td>
            <a href="<?= $this->url('main', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                <?= $this->escapeHtml($post->getText()); ?>
            </a> 
        </td>
        <td>
            <?= $this->escapeHtml($post->getTitle()); ?></a>
        </td>
        <td>
            <?= $this->escapeHtml($post->getLang()); ?></a>
        </td>
        <td><?= $this->escapeHtml($post->getImage()); ?></td>
        <td><nobr><?= $this->escapeHtml($post->getDateCreated()); ?></nobr></td>
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<?= $this->paginationControl($posts,
                    'Sliding',
                    'user/partial/paginator', 
                    array('route' => 'post')); ?>
