<?php
$this->headTitle('Users');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Posts'=>$this->url('main'),
            ]);
?>

<h1>Manage Posts</h1>

<p>
<a class="btn btn-default" href="
    <?= $this->url('main', ['action'=>'add']); ?>">
    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> New Post
</a>
</p>

<table class="table table-striped">

   <tr>
        <th>ID</th>
        <th>Type</th>
        <th>Text</th>
        <th>Title</th>
        <th>Language</th>
        <th>Image</th>
        <th>Date Created</th>
        <th>Actions</th>
    </tr>
    
    <?php foreach ($posts as $post): ?>
    
    <tr>
        <td><?= $this->escapeHtml($post->getId()); ?></td>
        <td>
            <?= $this->escapeHtml($post->getType()); ?></a>
        </td>
        <td>
            <a href="<?= $this->url('main', ['action'=>'view', 'id'=>$post->getId()]); ?>">
                <?= $this->escapeHtml($post->getText()); ?>
            </a> 
        </td>
        <td>
            <?= $this->escapeHtml($post->getTitle()); ?></a>
        </td>
        <td>
            <?= $this->escapeHtml($post->getLang()); ?></a>
        </td>
        <td><?= $this->escapeHtml($post->getImage()); ?></td>
        <td><nobr><?= $this->escapeHtml($post->getDateCreated()); ?></nobr></td>
        <td>
            <a class="btn btn-info" href="<?= $this->url('main',
                    ['action'=>'edit', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-pencil" ></span> Edit
            </a>
            <a class="btn btn-default" href="<?= $this->url('main',
                    ['action'=>'delete', 'id'=>$post->getId()]); ?>">
                <span class="glyphicon glyphicon-remove"></span> Delete
            </a>
        </td>
    </tr>
        
    <?php endforeach; ?>   
    
</table>

<?= $this->paginationControl($posts,
                    'Sliding',
                    'user/partial/paginator', 
                    array('route' => 'main')); ?>
