<?php
$this->headTitle('View Post');

$this->mainMenu()->setActiveItemId('admin');

$this->pageBreadcrumbs()->setItems([
            'Home'=>$this->url('home'),
            'Manage Posts'=>$this->url('main'),
            'View Post'=>$this->url('main', ['action'=>'view', 'id'=>$post->getId()])
            ]);
?>

<h1>View Post:  <?= $this->escapeHtml($post->getTitle()) ?></h1>

<p>
    <a class="btn btn-default" href="<?= $this->url('main',
            ['action'=>'edit', 'id'=>$post->getId()]); ?>">
        <span class="glyphicon glyphicon-pencil" ></span> Edit
    </a>
</p>

<div class="row">
    <div class="col-md-6">
        <table class="table table-striped table-bordered">
             <tr>
                <th>ID:</th>
                <td><?= $this->escapeHtml($post->getId()) ?></th>
            </tr>
            <tr>
                <th>Title:</th>
                <td><?= $this->escapeHtml($post->getTitle()) ?></th>
            </tr>
            <tr>
                <th>Text:</th>
                <td><?= $this->escapeHtml($post->getText()) ?></th>
            </tr>
            <tr>
                <th>Date Created:</th>
                <td><?= $this->escapeHtml($post->getDateCreated()) ?></th>
            </tr>
            <tr>
                <th>Type:</th>
                <td><?= $this->escapeHtml($post->getType()) ?></th>
            </tr>
            <tr>
                <th>Language:</th>
                <td><?= $this->escapeHtml($post->getLang()) ?></th>
            </tr>
            <tr>
                <th>Image:</th>
                <td><img src="<?php echo $this->basePath('../data/upload/images/'); ?><?= $this->escapeHtml($post->getImage()) ?>" alt="photo" height="100" width="100"></th>
            </tr>
            <tr>
                <th>File:</th>
                <td><a href="<?php echo $this->basePath('../data/upload/pdf/'); ?><?= $this->escapeHtml($post->getFile()) ?>" download>Download</a></th>
            </tr>
        </table>
    </div>
</div>